#!/bin/bash
# Building a star index file
# Define output and reference genome paths
genome_index_dir="/beegfs/data/fslimi/assembly/genome_index/"
genome_fasta="/beegfs/data/fslimi/assembly/fAlb15_MTmask_mtfZan.fasta"
gtf_file="/beegfs/data/fslimi/annotation/Ficedula_albicollis.fAlb15.e104.gtf"

# Create genome index with STAR
STAR --runMode genomeGenerate \
     --sjdbOverhang 100 \
     --genomeFastaFiles "$genome_fasta" \
     --genomeDir "$genome_index_dir" \
     --sjdbGTFfile "$gtf_file"
